"""Init

Revision ID: 5368449d3b94
Revises: de00fd141b54
Create Date: 2022-09-18 15:01:20.437636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5368449d3b94'
down_revision = 'de00fd141b54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
